### PR TITLE
removed trailing spaces

### PR DESCRIPTION
**Pull request by gn0st1c**
minor: removed trailing spaces

### CODE REVIEW

**Comment by tbowmo** [comment]
Thanks for the pr. 

I hope you can find your way around, after I restructured the project :)

**Comment by gn0st1c** [comment]
@tbowmo : great work :)

how about, say in mysdecode and msgOut.messageType, you also return msgOut.messageTypeStr = mysensor_command_str[messageType] which makes the output easier to read. (also easier publishing to mqtt without coding a separate conversion function)

proposal:
[mysensors-types.ts.zip](https://github.com/tbowmo/node-red-contrib-mysensors/files/1960693/mysensors-types.ts.zip)

**Comment by tbowmo** [comment]
Perhaps not that bad an idea.

**Comment by tbowmo** [comment]
Could you make a new issue with your suggestion, so I /we can track it?

**Pull request merged**
